export const getCurrencySymbol = (currencyCode: string): string => {
  switch (currencyCode) {
    case 'USD':
      return '$';
    case 'INR':
      return '₹';
    case 'EUR':
      return '€';
    case 'GBP':
      return '£';
    case 'CAD':
      return 'C$';
    case 'AUD':
      return 'A$';
    case 'JPY':
      return '¥';
    case 'CNY':
      return '¥';
    case 'KRW':
      return '₩';
    case 'RUB':
      return '₽';
    case 'BRL':
      return 'R$';
    case 'MXN':
      return '$';
    case 'SGD':
      return 'S$';
    case 'HKD':
      return 'HK$';
    case 'NZD':
      return 'NZ$';
    case 'CHF':
      return 'CHF';
    case 'SEK':
      return 'kr';
    case 'NOK':
      return 'kr';
    case 'DKK':
      return 'kr';
    case 'PLN':
      return 'zł';
    case 'CZK':
      return 'Kč';
    case 'HUF':
      return 'Ft';
    case 'RON':
      return 'lei';
    case 'BGN':
      return 'лв';
    case 'HRK':
      return 'kn';
    case 'RSD':
      return 'дин';
    case 'UAH':
      return '₴';
    case 'TRY':
      return '₺';
    case 'ILS':
      return '₪';
    case 'AED':
      return 'د.إ';
    case 'SAR':
      return 'ر.س';
    case 'QAR':
      return 'ر.ق';
    case 'KWD':
      return 'د.ك';
    case 'BHD':
      return '.د.ب';
    case 'OMR':
      return 'ر.ع.';
    case 'JOD':
      return 'د.ا';
    case 'LBP':
      return 'ل.ل';
    case 'EGP':
      return 'ج.م';
    case 'ZAR':
      return 'R';
    case 'NGN':
      return '₦';
    case 'KES':
      return 'KSh';
    case 'GHS':
      return 'GH₵';
    case 'UGX':
      return 'USh';
    case 'TZS':
      return 'TSh';
    case 'ZMW':
      return 'ZK';
    case 'BWP':
      return 'P';
    case 'NAD':
      return 'N$';
    case 'MUR':
      return '₨';
    case 'SCR':
      return '₨';
    case 'SZL':
      return 'L';
    case 'LSL':
      return 'L';
    case 'MAD':
      return 'د.م.';
    case 'TND':
      return 'د.ت';
    case 'DZD':
      return 'د.ج';
    case 'LYD':
      return 'د.ل';
    case 'SDG':
      return 'ج.س.';
    case 'ETB':
      return 'Br';
    case 'TND':
      return 'د.ت';
    case 'MAD':
      return 'د.م.';
    case 'DZD':
      return 'د.ج';
    case 'LYD':
      return 'د.ل';
    case 'SDG':
      return 'ج.س.';
    case 'ETB':
      return 'Br';
    default:
      return '$';
  }
};

export const getCurrencyForMode = (
  selectedMode: 'local' | 'home',
  primaryCurrency: string,
  homeCurrency: string
): string => {
  return selectedMode === 'home' ? homeCurrency : primaryCurrency;
}; 